# Current monotor: (1080 x 1920)
display_width: 1080
display_height: 1920

# How often to display a new image in (seconds)
recording_duration: 30

# How much of the recording should be repeated (must be less than `portrait_refresh`)
playback_duration: 10
